// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: envlookup.proto

package envlookup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnvLookupClient is the client API for EnvLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvLookupClient interface {
	GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error)
}

type envLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvLookupClient(cc grpc.ClientConnInterface) EnvLookupClient {
	return &envLookupClient{cc}
}

func (c *envLookupClient) GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error) {
	out := new(GetEnvResponse)
	err := c.cc.Invoke(ctx, "/EnvLookup/GetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvLookupServer is the server API for EnvLookup service.
// All implementations must embed UnimplementedEnvLookupServer
// for forward compatibility
type EnvLookupServer interface {
	GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error)
	mustEmbedUnimplementedEnvLookupServer()
}

// UnimplementedEnvLookupServer must be embedded to have forward compatible implementations.
type UnimplementedEnvLookupServer struct {
}

func (UnimplementedEnvLookupServer) GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnv not implemented")
}
func (UnimplementedEnvLookupServer) mustEmbedUnimplementedEnvLookupServer() {}

// UnsafeEnvLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvLookupServer will
// result in compilation errors.
type UnsafeEnvLookupServer interface {
	mustEmbedUnimplementedEnvLookupServer()
}

func RegisterEnvLookupServer(s grpc.ServiceRegistrar, srv EnvLookupServer) {
	s.RegisterService(&EnvLookup_ServiceDesc, srv)
}

func _EnvLookup_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvLookupServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EnvLookup/GetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvLookupServer).GetEnv(ctx, req.(*GetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvLookup_ServiceDesc is the grpc.ServiceDesc for EnvLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EnvLookup",
	HandlerType: (*EnvLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnv",
			Handler:    _EnvLookup_GetEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "envlookup.proto",
}
